WebPagesPack/Models/JbzdyViewModel.cs
using Models;
using System.Collections.Generic;


namespace WebPagesPack.Models
{
    public class JbzdyViewModel
    {
        public IEnumerable<JbzdyModel> JbzdyList { get; set; }

        public int CurrentPageNumber { get; set; }
    }
}

WebPagesPack/Models/KwejkViewModel.cs
using Models;
using System.Collections.Generic;


namespace WebPagesPack.Models
{
    public class KwejkViewModel
    {
        public IEnumerable<KwejkModel> KwejkList { get; set; }

        public int CurrentPageNumber { get; set; }
    }
}

WebPagesPack/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebPagesPack.Controllers
{
    public class HomeController:Controller
    {

        public ViewResult Index()
        {
            return View();
        }
    }
}

WebPagesPack/Controllers/JbzdyController.cs
using HtmlParser.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebPagesPack.Models;

namespace WebPagesPack.Controllers
{
    public class JbzdyController: Controller
    {
        public int FirstPageNumber { get; set; }
        private IJbzdyRepository jzbdyRepo;

        public JbzdyController(IJbzdyRepository repo)
        {
            jzbdyRepo = repo;
        }

        public ViewResult Index(int? id)
        {

            var model = id == null ? jzbdyRepo.GetObjects().ToList() : jzbdyRepo.GetObjects((int)id).ToList();
            var viewModel = new JbzdyViewModel { JbzdyList = model, CurrentPageNumber = FirstPageNumber };
            //model.CurrentPageNumber = id == null ? FirstPageNumber : (int)id;

            return View(viewModel);
        }

        public ActionResult GetPage(int id)
        {
            var model = jzbdyRepo.GetObjects(id);
            var viewModel = new JbzdyViewModel { JbzdyList = model, CurrentPageNumber = id };

            return PartialView("Index", viewModel);
        }
    }
}

WebPagesPack/Controllers/KwejkController.cs
using Microsoft.AspNetCore.Mvc;
using HtmlParser.Interfaces;
using System.Linq;
using WebPagesPack.Models;

namespace WebPagesPack.Controllers
{
    public class KwejkController: Controller
    {

        public int FirstPageNumber { get; set; }
        private IKwejkRepository kwejkRepo;

        public KwejkController(IKwejkRepository kwejkRepo)
        {
            this.kwejkRepo = kwejkRepo;
            FirstPageNumber = kwejkRepo.GetFirstPageNumber();
        }

        public ViewResult Index(int? id)
        {

            var model = id == null ? kwejkRepo.GetObjects().ToList() : kwejkRepo.GetObjects((int)id).ToList();
            var viewModel = new KwejkViewModel { KwejkList = model, CurrentPageNumber = FirstPageNumber };
            //model.CurrentPageNumber = id == null ? FirstPageNumber : (int)id;

            return View(viewModel);
        }

        public ActionResult GetPage(int id)
        {
            var model = kwejkRepo.GetObjects(id);
            var viewModel = new KwejkViewModel { KwejkList = model, CurrentPageNumber = id };

            return PartialView("Index", viewModel);
        }
    }
}

WebPagesPack/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Choose Wisely";
}

<div class="col-12 text-center align-top" style="margin-top: 10vh;">
    <a href="@Url.Action("Index","Kwejk")">
        <img src="~/Images/kwejk_logo.png" class="img-fluid enlargingOnHover"/>
    </a>
</div>

<div class="col-12 text-center align-top" style="margin-top: 10vh;">
    <a href="@Url.Action("Index","Jbzdy")">
        <img src="~/Images/jbzdy_logo.png" class="img-fluid enlargingOnHover" />
    </a>
</div>

WebPagesPack/Views/Home/KwejkScripts.cshtml
@model WebPagesPack.Models.IndexViewModel
<script>
    let currentPage;
    let Url;
    let documentHeight = 0;

    $(document).ready(function () {
        currentPage = @Model.CurrentPageNumber;
    })

    $(window).scroll(function () {
        if ($(document).scrollTop() > $(document).height() - 3000 && documentHeight !== $(document).height()) {

            currentPage--
            $.get("/Home/GetPage/" + currentPage, function (data) {
                $("div#loading").remove();
                $("div.PageContent").append(data);
            });
            
            documentHeight = $(document).height();
        }
    });

</script>

WebPagesPack/Views/Jbzdy/Index.cshtml
@model JbzdyViewModel
@{
    ViewData["Title"] = "Index";
}

    <div class="col-12 text-center">
        @foreach (var item in Model.JbzdyList)
        {
            if (item.ImageUrl != null)
            {
                <div class="bottom-top-padding">
                    <h3 class="text-white">@item.Title</h3>
                    <img src="@item.ImageUrl" class="border border-larger img-fluid" />
                </div>
            }
            else if (item.VideoUrl != null)
            {
                <div class="bottom-top-padding">
                    <h3 class="text-white">@item.Title</h3>
                    <video class="text-center border border-larger img-fluid" width="612" controls>
                        <source src="@item.VideoUrl" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
            }
            else
            {
                <div class="bottom-top-padding">
                    <h3 class="text-white">Coś tu nie zadziałało</h3>
                    <div class="border border-larger">  </div>
                </div>
            }

        }
    </div>

WebPagesPack/Views/Kwejk/Index.cshtml
@model KwejkViewModel

@{
    ViewData["Title"] = "Memsy";
}

<div class="col-12 text-center">
    @foreach (var item in Model.KwejkList)
    {
        if (item.ImageUrl != null)
        {
            <div class="bottom-top-padding">
                <h3 class="text-white">@item.Title</h3>
                <img src="@item.ImageUrl" class="border border-larger img-fluid" />
            </div>
        }
        else if (item.VideoUrl != null)
        {
            <div class="bottom-top-padding">
                <h3 class="text-white">@item.Title</h3>
                <video class="text-center border border-larger img-fluid" width="612" controls>
                    <source src="@item.VideoUrl" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        }
        else
        {
            <div class="bottom-top-padding">
                <h3 class="text-white">Coś tu nie zadziałało</h3>
                <div class="border border-larger">  </div>
            </div>
        }

    }
</div>

<div class="col-12 text-center" id="loading">
    <img class="shrinkedImage" id="loading-gif" src="~/Images/loading.gif">
</div>

@section scripts
{
    @Html.RenderPartialAsync("KwejkScripts", Model)
}

WebPagesPack/Views/Kwejk/KwejkScripts.cshtml
@model WebPagesPack.Models.KwejkViewModel
<script>
    let currentPage;
    let Url;
    let documentHeight = 0;

    $(document).ready(function () {
        currentPage = @Model.CurrentPageNumber;
    })

    $(window).scroll(function () {
        if ($(document).scrollTop() > $(document).height() - 3000 && documentHeight !== $(document).height()) {

            currentPage--
            $.get("/Kwejk/GetPage/" + currentPage, function (data) {
                $("div#loading").remove();
                $("div.PageContent").append(data);
            });
            
            documentHeight = $(document).height();
        }
    });

</script>

WebPagesPack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          href="~/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet"
          href="~/lib/GlobalStyles.css" />
    
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <title>@ViewData["Title"]</title>
</head>
<body>

    <div class="row m-1 p-1 PageContent">
        @RenderBody()
    </div>

    @RenderSection("scripts", false)
    
</body>
</html>